#!/bin/bash

# ----------------------------------------------------------------------------
# battery: show battery remaining
# ----------------------------------------------------------------------------

echo "$(acpi --battery | awk '{print $4}' | sed 's/%.*$//')%"

# vim: set filetype=sh foldmethod=marker foldlevel=0 nowrap:
