#!/bin/bash

# ----------------------------------------------------------------------------
# interface: show inet interface
# ----------------------------------------------------------------------------

set -o pipefail

main() {
  ip -o -4 route show to default 2>/dev/null \
    | tr '[:space:]' '\n' \
    | sed -n '/dev/{n;p}'
}

main

# vim: set filetype=sh foldmethod=marker foldlevel=0 nowrap:
