#!/bin/bash

# ----------------------------------------------------------------------------
# macaddr: show hardware MAC address
# ----------------------------------------------------------------------------

main() {
  local _interface
  _interface="${1:-$INTERFACE}"
  if [[ -n "$_interface" ]]; then
    ip -0 addr show dev "$_interface" \
      | awk '/link/ && /ether/ {print $2}' \
      | tr '[:upper:]' '[:lower:]'
  else
    exit 1
  fi
}

main "$1"
