#!/bin/bash

# ----------------------------------------------------------------------------
# macaddr: show hardware MAC address
# ----------------------------------------------------------------------------

set -o pipefail

main() {
  local _interface
  _interface="${1:-$INTERFACE}"
  if [[ -n "$_interface" ]]; then
    ip -0 addr show dev "$_interface" 2>/dev/null \
      | awk '/link/ && /ether/ {print $2}' \
      | tr '[:upper:]' '[:lower:]'
  else
    exit 1
  fi
}

main "$1"

# vim: set filetype=sh foldmethod=marker foldlevel=0 nowrap:
