#!/bin/bash

# ----------------------------------------------------------------------------
# macaddr: show hardware MAC address
# ----------------------------------------------------------------------------

ip -0 addr show dev "$INTERFACE" \
  | awk '/link/ && /ether/ {print $2}' \
  | tr '[:upper:]' '[:lower:]'
